<?php

namespace App\Model;

use Optix\Media\HasMedia;
use Optix\Media\Models\Media as BaseMedia;
class Media extends BaseMedia
{
    use HasMedia;

    public function registerMediaGroups()
    {
        $this->addMediaGroup('gallery')
            ->performConversions('thumb','thumb_250');

    }
    /**
     * Get the directory for files on disk.
     *
     * @return mixed
     */
    public function getDirectory()
    {
        return $this->created_at->format('Y-M');
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
